FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN curl -fsSL https://get.docker.com | sh

# Copy plugins.txt
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install plugins
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

USER jenkins
